### ISSUE TITLE
Need a page describing what an e-Laboratory is

### ISSUE THREAD

**Issue by shoaibsufi** [eScienceLab/eScienceLab.github.io#38]
There are some references:

http://www.herc.ac.uk/research_project/elab/ 

and

http://health.knowledgeblog.org/2011/05/16/what-is-an-e-lab-how-can-it-help-you/

But eScience Lab make such a heavy reference to this being the type of product that we make, we need to own the definition a bit more than we do at the moment.

We need to link to this definition form the front page, about pages and footer

**Comment by shoaibsufi** [comment]
About and Index page have been updated explaining what an e-Lab is - but a better explanation with some resources would be better in the long term

**Comment by alaninmcr** [comment]
There is a whole load of stuff under http://www.mygrid.org.uk/tools/e-labs/ . I have little idea how much is true.
